### ISSUE TITLE
bundleAssets fails with css like bootstrap's

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#91]
I think it is related to how they are adding font-faces.

**Comment by matthewp** [comment]
This is probably the offending css:

```css
@font-face {
  font-family: 'Glyphicons Halflings';

  src: url('../fonts/glyphicons-halflings-regular.eot');
  src: url('../fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('../fonts/glyphicons-halflings-regular.woff2') format('woff2'), url('../fonts/glyphicons-halflings-regular.woff') format('woff'), url('../fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
```

I bet the regex [here](https://github.com/stealjs/steal-bundler/blob/master/lib/css.js#L4) is not detecting the `#` and `?` symbols.
